version: 0.0
os: linux

files:
- source: /
  destination: /home/centos/webapp

hooks:
AfterInstall:
- location: /home/centos/webapp/infrastructure/aws/codedeploy/afterInstall.sh
  timeout: 180
  runas: root
ApplicationStart:
- location: /home/centos/webapp/infrastructure/aws/codedeploy/applicationStart.sh
  timeout: 180
  runas: centos