version: 0.0
os: linux

files:
- source: /
  destination: /home/centos
permissions:
- object: /home/centos
  owner: centos
  group: centos
type:
- directory
- file
hooks:
AfterInstall:
- location: ./infrastructure/aws/codedeploy/afterInstall.sh
  timeout: 180
  runas: root
ApplicationStart:
- location: ./infrastructure/aws/codedeploy/applicationStart.sh
  timeout: 180
  runas: centos