version: 0.0
os: linux

files:
 - source: ./webapp
   destination: /home/centos/

permissions:
 - object: /home/centos/webapp
   owner: centos
   group: centos
   mode: 700
   type:
    - file
 - object: /home/centos/webapp
   owner: centos
   group: centos
   mode: 700
   type:
    - directory

hooks:
AfterInstall:
- location: ./afterInstall.sh
  timeout: 180
  runas: centos
ApplicationStart:
- location: ./applicationStart.sh
  timeout: 3600
  runas: centos
ApplicationStop:
- location: ./applicationStop.sh
  timeout: 3600
  runas: centos